#lang racket
(provide matching-engine%)
(require stockfighter-api "orderbook.rkt" "utils.rkt" racket/generator data/heap
         net/rfc6455 (only-in json jsexpr->string))

(define matching-engine%
  (class object% (super-new)
    (init-field orderbook)
    (field [orders (make-hash)]
           [next-id 0]
           [last-trade-data (make-hash (list (cons `last 0) (cons `lastSize 0) (cons `lastTrade "")))])
    (define/public (get-orders)  orders)
    (define/public (get-orderbook) orderbook)
    (define/public (get-order-status id)
      (hash-ref orders id (error-json "order not found")))

    (define (send-execution inst e)
      (define executions (hash-ref (instance-executions-sockets inst) (order-account e) #f))
      (unless (false? executions)
        (if (ws-conn-closed? executions)
            (hash-set! (instance-executions-sockets inst) (order-account e) #f)
            (with-handlers ([exn? (lambda (e) (hash-set! (instance-executions-sockets inst) (order-account e) #f))])
              (ws-send! executions (jsexpr->string e))))))
    
    (define/public (cancel-order inst id account)
      (define order (hash-ref orders id #f))
      (if (equal? #f order)
          (error-json "order not found")
          (if (not (equal? account (order-account order)))
              (error-json "cannot cancel another trader's order")
              (begin (hash-set! order `open #f) (hash-set! orders id order) (orderbook-remove! orderbook id) order))))

    (define/public (display)
      (displayln "bids:")
      (print-bids orderbook)
      (displayln "asks:")
      (print-asks orderbook))
    
    (define/public (get-last-trade) last-trade-data)
    
    (define/public (handle-order inst o)
      (unless (hash-has-key? o `price) (hash-set! o `price 0))
      (hash-set! o `ok #t)
      (hash-set! o `ts (current-time->string))
      (hash-set! o `fills null)
      (hash-set! o `originalQty (order-qty o))
      (hash-set! o `open #t)
      (hash-set! o `id next-id)
      (set! next-id (+ 1 next-id))
      (define type (order-type o))
      (cond [(< (order-price o) 0) (error-json "order price must be non-negative")]
            [(<= (order-qty o) 0) (error-json "order size must be greater than 0")]
            [(and (not (equal? type "limit")) (not (equal? type "market")) (not (equal? type "fill-or-kill")) (not (equal? type "immediate-or-cancel")))
             (error-json "unknown order type")]
            [(equal? "buy" (order-direction o)) (handle-bid inst o)]
            [(equal? "sell" (order-direction o)) (handle-ask inst o)]
            [else (error-json (string-append "unknown order direction, try buy or sell"))]))
    
    (define/public (handle-bid inst b)
      (hash-set! orders (order-id b) b)
      (cond [(= 0 (heap-count (orderbook-asks orderbook)))
             (cond [(equal? "limit" (order-type b))
                    (orderbook-add-bid! orderbook b) b]
                   [else (hash-set! b `open #f) b])]
            [(equal? "market" (order-type b)) (cross-bid b inst)]
            [(and (not (equal? "market" (order-type b))) (<= (order-price (orderbook-get-best-ask orderbook)) (order-price b)))
             (cross-bid b inst)]
            [(equal? "limit" (order-type b)) (orderbook-add-bid! orderbook b) b]
            [else (hash-set! b `open #f)
                  b]))
    
    (define/public (handle-ask inst a)
      (hash-set! orders (order-id a) a)
      (cond [(= 0 (heap-count (orderbook-bids orderbook)))
             (cond [(equal? "limit" (order-type a))
                    (orderbook-add-ask! orderbook a) a]
                   [else (hash-set! a `open #f) a])]
            [(equal? "market" (order-type a)) (cross-bid a inst)]
            [(and (not (equal? "market" (order-type a))) (<= (order-price a) (order-price (orderbook-get-best-bid orderbook))))
             (cross-ask a inst)]
            [(equal? "limit" (order-type a)) (orderbook-add-ask! orderbook a) a]
            [else (hash-set! a `open #f)
                  a]))
    
    (define/public (cross-ask a inst [fok-checked? #f])
      (define best-bid (orderbook-get-best-bid orderbook))
      (unless (or (false? best-bid) (void? best-bid))
        (if (and (equal? "fill-or-kill" (order-type a)) (false? fok-checked?))
            (let ([qty 0])
              (for ([bid (in-heap (orderbook-bids orderbook))])
                (when (>= (order-price bid) (order-price a))
                  (set! qty (+ qty (order-qty bid)))))
              (if (>= qty (order-original-qty a))
                  (cross-ask a #t)
                  (begin  (hash-set! a `fills null)
                    (hash-set! a `qty (hash-ref a `originalQty))
                    a)))
            (cond [(= (order-qty best-bid) (order-qty a))
                   (let ([bb (orderbook-remove-best-bid orderbook)])
                     (unless (or (false? bb)  (void? bb))
                       (hash-set! bb `fills (append (order-fills bb) (list (make-hash (list (cons `price (order-price bb))
                                                                                            (cons `qty (order-qty a))
                                                                                            (cons `ts (current-time->string)))))))
                       (hash-set! a `fills (append (hash-ref a `fills null) (list (make-hash (list (cons `price (order-price bb))
                                                                                                   (cons `qty (order-qty bb))
                                                                                                   (cons `ts (current-time->string)))))))
                       (hash-set! last-trade-data `last (order-price bb))
                       (hash-set! last-trade-data `lastSize (order-qty bb))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! a `qty 0)
                       (hash-set! bb `qty 0)
                       (hash-set! orders (order-id a) a)
                       (hash-set! orders (order-id bb) bb)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account bb) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account bb))
                                                                  (cons `symbol (order-symbol bb))
                                                                  (cons `venue (order-venue bb))
                                                                  (cons `price (order-price bb))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order bb)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id bb))
                                                                  (cons `incomingID (order-id a))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account a) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account a))
                                                                  (cons `symbol (order-symbol a))
                                                                  (cons `venue (order-venue a))
                                                                  (cons `price (order-price bb))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order a)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id bb))
                                                                  (cons `incomingID (order-id a))))))
                       a))]
                       ; (list bb a)))]
                  [(< (order-qty best-bid) (order-qty a))
                   (let* ([bb0 (orderbook-remove-best-bid orderbook)])
                     (unless (or (false? bb0)  (void? bb0))
                       (hash-set! bb0 `fills (append (order-fills bb0) (list (make-hash (list (cons `price (order-price bb0))
                                                                                              (cons `qty (order-qty bb0))
                                                                                              (cons `ts (current-time->string)))))))
                       (hash-set! a `fills (append (hash-ref a `fills null) (list (make-hash (list (cons `price (order-price bb0))
                                                                                                   (cons `qty (order-qty bb0))
                                                                                                   (cons `ts (current-time->string)))))))
                       
                       (hash-set! last-trade-data `last (order-price bb0))
                       (hash-set! last-trade-data `lastSize (order-qty bb0))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! a `qty (- (order-qty a) (order-qty bb0)))
                       (hash-set! bb0 `qty 0)
                       (hash-set! bb0 `open #f)
                       (hash-set! orders (order-id a) a)
                       (hash-set! orders (order-id bb0) bb0)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account bb0) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account bb0))
                                                                  (cons `symbol (order-symbol bb0))
                                                                  (cons `venue (order-venue bb0))
                                                                  (cons `price (order-price bb0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order bb0)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #f)
                                                                  (cons `standingID (order-id bb0))
                                                                  (cons `incomingID (order-id a))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account a) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account a))
                                                                  (cons `symbol (order-symbol a))
                                                                  (cons `venue (order-venue a))
                                                                  (cons `price (order-price bb0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order a)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #f)
                                                                  (cons `standingID (order-id bb0))
                                                                  (cons `incomingID (order-id a))))))
                       a))]
                      ; (append (list bb0) (handle-ask a))))]
                  [else
                   (let* ([bb0 (orderbook-remove-best-bid orderbook)])
                     (unless (or (false? bb0)  (void? bb0))
                       (hash-set! bb0 `fills (append (order-fills bb0) (list (make-hash (list (cons `price (order-price bb0))
                                                                                              (cons `qty (order-qty a))
                                                                                              (cons `ts (current-time->string)))))))
                       (hash-set! a `fills (append (hash-ref a `fills null) (list (make-hash (list (cons `price (order-price bb0))
                                                                                                   (cons `qty (order-qty a))
                                                                                                   (cons `ts (current-time->string)))))))
                       
                       (hash-set! last-trade-data `last (order-price bb0))
                       (hash-set! last-trade-data `lastSize (order-original-qty a))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! bb0 `qty (- (order-qty bb0) (order-qty a)))
                       (hash-set! a `qty 0)
                       (hash-set! a `open #f)
                       (orderbook-add-bid! orderbook bb0)
                       (hash-set! orders (order-id a) a)
                       (hash-set! orders (order-id bb0) bb0)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account bb0) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account bb0))
                                                                  (cons `symbol (order-symbol bb0))
                                                                  (cons `venue (order-venue bb0))
                                                                  (cons `price (order-price bb0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order bb0)
                                                                  (cons `standingComplete #f)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id bb0))
                                                                  (cons `incomingID (order-id a))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account a) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account a))
                                                                  (cons `symbol (order-symbol a))
                                                                  (cons `venue (order-venue a))
                                                                  (cons `price (order-price bb0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order a)
                                                                  (cons `standingComplete #f)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id bb0))
                                                                  (cons `incomingID (order-id a))))))
                       a))]))))
                       ;(list a bb0)))]))))

    (define/public (cross-bid b inst [fok-checked? #f])
      (define best-ask (orderbook-get-best-ask orderbook))
      (unless (or (false? best-ask) (void? best-ask))
        (if (and (equal? "fill-or-kill" (order-type b)) (false? fok-checked?))
            (let ([qty 0])
              (for ([ask (in-heap (orderbook-asks orderbook))])
                (when (<= (order-price ask) (order-price b))
                  (set! qty (+ qty (order-qty ask)))))
              (if (>= qty (order-original-qty b))
                  (cross-bid b #t)
                  (begin (hash-set! b `fills null)
                         (hash-set! b `qty (hash-ref b `originalQty))
                         b)))
            (cond [(= (order-qty best-ask) (order-qty b))
                   (let ([ba (orderbook-remove-best-ask orderbook)])
                     (unless (or (false? ba)  (void? ba))
                       (hash-set! ba `fills (append (order-fills ba) (list (make-hash (list (cons `price (order-price ba))
                                                                                            (cons `qty (order-qty b))
                                                                                            (cons `ts (current-time->string)))))))
                       
                       (hash-set! b `fills (append (hash-ref b `fills null) (list (make-hash (list (cons `price (order-price ba))
                                                                                                   (cons `qty (order-qty ba))
                                                                                                   (cons `ts (current-time->string)))))))
                       
                       (hash-set! last-trade-data `last (order-price ba))
                       (hash-set! last-trade-data `lastSize (order-qty ba))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! b `qty 0)
                       (hash-set! ba `qty 0)
                       (hash-set! orders (order-id b) b)
                       (hash-set! orders (order-id ba) ba)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account ba) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account ba))
                                                                  (cons `symbol (order-symbol ba))
                                                                  (cons `venue (order-venue ba))
                                                                  (cons `price (order-price ba))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order ba)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id ba))
                                                                  (cons `incomingID (order-id b))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account b) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account b))
                                                                  (cons `symbol (order-symbol b))
                                                                  (cons `venue (order-venue b))
                                                                  (cons `price (order-price ba))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order b)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id ba))
                                                                  (cons `incomingID (order-id b))))))
                       b))]
                  [(< (order-qty best-ask) (order-qty b))
                   (let* ([ba0 (orderbook-remove-best-ask orderbook)])
                     (unless (or (false? ba0)  (void? ba0))
                       
                       (hash-set! ba0 `fills (append (order-fills ba0) (list (make-hash (list (cons `price (order-price ba0))
                                                                                              (cons `qty (order-qty ba0))
                                                                                              (cons `ts (current-time->string)))))))
                       (hash-set! b `fills (append (hash-ref b `fills null) (list (make-hash (list (cons `price (order-price ba0))
                                                                                                   (cons `qty (order-qty ba0))
                                                                                                   (cons `ts (current-time->string)))))))

                       (hash-set! last-trade-data `last (order-price ba0))
                       (hash-set! last-trade-data `lastSize (order-qty ba0))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! b `qty (- (order-qty b) (order-qty ba0)))
                       (hash-set! ba0 `open #f)
                       (hash-set! ba0 `qty 0)
                       (hash-set! orders (order-id b) b)
                       (hash-set! orders (order-id ba0) ba0)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account ba0) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account ba0))
                                                                  (cons `symbol (order-symbol ba0))
                                                                  (cons `venue (order-venue ba0))
                                                                  (cons `price (order-price ba0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order ba0)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #f)
                                                                  (cons `standingID (order-id ba0))
                                                                  (cons `incomingID (order-id b))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account b) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account b))
                                                                  (cons `symbol (order-symbol b))
                                                                  (cons `venue (order-venue b))
                                                                  (cons `price (order-price ba0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order b)
                                                                  (cons `standingComplete #t)
                                                                  (cons `incomingComplete #f)
                                                                  (cons `standingID (order-id ba0))
                                                                  (cons `incomingID (order-id b))))))
                       b))]
                  [else
                   (let ([ba0 (orderbook-remove-best-ask orderbook)])
                     (unless (or (false? ba0)  (void? ba0))
                       (hash-set! b `fills (append (hash-ref b `fills null) (list (make-hash (list (cons `price (order-price ba0))
                                                                                                   (cons `qty (order-qty b))
                                                                                                   (cons `ts (current-time->string)))))))
                       (hash-set! ba0 `fills (append (order-fills ba0) (list (make-hash (list (cons `price (order-price ba0))
                                                                                              (cons `qty (order-qty b))
                                                                                              (cons `ts (current-time->string)))))))
                       

                       (hash-set! last-trade-data `last (order-price ba0))
                       (hash-set! last-trade-data `lastSize (order-original-qty b))
                       (hash-set! last-trade-data `lastTrade (current-time->string))
                       (hash-set! ba0 `qty (- (order-qty ba0) (order-qty b)))
                       (hash-set! b `qty 0)
                       (hash-set! b `open #f)
                       (hash-set! orders (order-id b) b)
                       (hash-set! orders (order-id ba0) ba0)
                       (orderbook-add-ask! orderbook ba0)
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account ba0) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account ba0))
                                                                  (cons `symbol (order-symbol ba0))
                                                                  (cons `venue (order-venue ba0))
                                                                  (cons `price (order-price ba0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order ba0)
                                                                  (cons `standingComplete #f)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id ba0))
                                                                  (cons `incomingID (order-id b))))))
                       (unless (false? (hash-ref (instance-executions-sockets inst) (order-account b) #f))
                         (send-execution inst (make-hash (list (cons `ok #t)
                                                                  (cons `account (order-account b))
                                                                  (cons `symbol (order-symbol b))
                                                                  (cons `venue (order-venue b))
                                                                  (cons `price (order-price ba0))
                                                                  (cons `filledAt (hash-ref last-trade-data `lastTrade))
                                                                  (cons `filled (hash-ref last-trade-data `lastSize))
                                                                  (cons `order b)
                                                                  (cons `standingComplete #f)
                                                                  (cons `incomingComplete #t)
                                                                  (cons `standingID (order-id ba0))
                                                                  (cons `incomingID (order-id b))))))
                       b))]))))))
          

(module+ test
  (require math)
  (define me (new matching-engine% [orderbook (new-orderbook)]))
  (define order-generator (generator ()
                                     (let loop ([id 0])
                                       (yield (make-hash
                                               (list 
                                                (cons `price (random-integer 100 200))
                                                (cons `orderType "limit")
                                                (cons `fills null)
                                                (cons `venue "IBQEX")
                                                (cons `direction (if (= 1 (random 2)) "buy" "sell"))
                                                (cons `account "IFL33491586")
                                                (cons `qty (random 21)))))
                                               (loop (+ 1 id)))))
   (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "limit")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "sell")
                          (cons `account "IFL33491586")
                          (cons `qty 11))))
   (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "market")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "buy")
                          (cons `account "IFL33491586")
                          (cons `qty 20))))
    (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "limit")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "sell")
                          (cons `account "IFL33491586")
                          (cons `qty 11))))
   (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "market")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "buy")
                          (cons `account "IFL33491586")
                          (cons `qty 20))))
  (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "limit")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "sell")
                          (cons `account "IFL33491586")
                          (cons `qty 11))))
  (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "fill-or-kill")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "buy")
                          (cons `account "IFL33491586")
                          (cons `qty 20))))
  (send me handle-order (make-hash
                         (list
                          (cons `price 1299)
                          (cons `orderType "immediate-or-cancel")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "buy")
                          (cons `account "IFL33491586")
                          (cons `qty 20))))
  (send me handle-order (make-hash
                         (list 
                          (cons `price 1299)
                          (cons `orderType "limit")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "sell")
                          (cons `account "IFL33491586")
                          (cons `qty 11))))
   (send me handle-order (make-hash
                          (list 
                           (cons `price 1299)
                           (cons `orderType "limit")
                           (cons `fills null)
                           (cons `venue "IBQEX")
                           (cons `direction "sell")
                           (cons `account "IFL33491586")
                           (cons `qty 9))))
  (send me handle-order (make-hash
                         (list 
                          (cons `price 1300)
                          (cons `orderType "limit")
                          (cons `fills null)
                          (cons `venue "IBQEX")
                          (cons `direction "buy")
                          (cons `account "IFL33491586")
                          (cons `qty 20))))
   (send me handle-order (make-hash
                          (list 
                           (cons `price 1300)
                           (cons `orderType "limit")
                           (cons `fills null)
                           (cons `venue "IBQEX")
                           (cons `direction "buy")
                           (cons `account "IFL33491586")
                           (cons `qty 20))))
  (send me handle-order (make-hash
                          (list 
                           (cons `price 1300)
                           (cons `orderType "limit")
                           (cons `fills null)
                           (cons `venue "IBQEX")
                           (cons `direction "buy")
                           (cons `account "IFL33491586")
                           (cons `qty 20))))
   (send me handle-order (make-hash
                          (list 
                           (cons `price 1289)
                           (cons `orderType "limit")
                           (cons `fills null)
                           (cons `venue "IBQEX")
                           (cons `direction "sell")
                           (cons `account "IFL33491586")
                           (cons `qty 5))))
  (send me display)
  (send me get-order-status 6))